name = "FixedMeshRefinement"
uuid = "ffe09bc1-ac12-45d3-a3dd-425211443744"
authors = ["Zhen Zhong <auroradysis@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
BlockArrays = "^1"
FastBroadcast = "^0.3"
LinearAlgebra = "^1"
OffsetArrays = "^1"
Printf = "^1"
julia = "1.10,1.11,1.12"
